### ISSUE TITLE
jspare-4vertx-web - Erro ao efetuar uma chamada com @ArrayModel

### ISSUE THREAD

**Issue by kairanTT** [jspare-projects/jspare-4vertx#1]
Ao enviar um Json array com um formatter inválido para o Gson, não é exibido nenhuma exceção, não tendo como saber o que aconteceu...

DefaultHandler:280

**Comment by pflima92** [comment]
Hi Kairan,

We already fixed this issue with release 2.0.0.

Migrate your project to up to date. 

Regards.
